spring:
  application:
    name: Uber-WebSocketService

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka service url

  instance:
    prefer-ip-address: true