{
  "formatVersion": "1.1",
  "component": {
    "group": "org.shakti",
    "module": "Uber-CommonLibraries",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Uber-CommonLibraries-0.0.1-SNAPSHOT-plain.jar",
          "url": "Uber-CommonLibraries-0.0.1-SNAPSHOT-plain.jar",
          "size": 15631,
          "sha512": "50b59074fc20517ff4f160e4ca50029a338c473fead797ca16ba137ad4625a25d89540242ab06b19fb0c730be812e3ebe2a67fbeff525a6859e2d220b7ee3aba",
          "sha256": "1f4b4253b40669b63e61500d947d6f9c03fe21ec4904478fcb4efbc6c92eddc1",
          "sha1": "7aabe3fa983ae564d32599cbc3a497d6e3cff0ee",
          "md5": "adc16182e1342b26fe0629f5f6fbc947"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "Uber-CommonLibraries-0.0.1-SNAPSHOT-plain.jar",
          "url": "Uber-CommonLibraries-0.0.1-SNAPSHOT-plain.jar",
          "size": 15631,
          "sha512": "50b59074fc20517ff4f160e4ca50029a338c473fead797ca16ba137ad4625a25d89540242ab06b19fb0c730be812e3ebe2a67fbeff525a6859e2d220b7ee3aba",
          "sha256": "1f4b4253b40669b63e61500d947d6f9c03fe21ec4904478fcb4efbc6c92eddc1",
          "sha1": "7aabe3fa983ae564d32599cbc3a497d6e3cff0ee",
          "md5": "adc16182e1342b26fe0629f5f6fbc947"
        }
      ]
    }
  ]
}
