plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.shakti'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-devtools:3.5.0'

    // Lombok - Required for IDE and compile-time processing
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.mysql:mysql-connector-j:9.3.0'

    implementation("org.springframework.boot:spring-boot-starter-security:3.5.0")
    implementation("io.jsonwebtoken:jjwt:0.12.6")

    // adding common library dependency here using groupid+artifactId+version
    //group + version -> build.gradle
    // artifactId -> application.properties (name of the project)
    implementation("org.shakti:Uber-CommonLibraries:0.0.2-SNAPSHOT")
}

tasks.named('test') {
    useJUnitPlatform()
}
